"""Parâmetros canônicos do runtime desktop Windows/Linux."""

CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080
CAMERA_FPS = 20
CAMERA_RESOLUTION_FALLBACKS = (
    (1920, 1080),
)
WINDOWS_PREFERRED_CAMERA_INDEX = 1
CAMERA_SCAN_MAX_INDEX = 3

FRAME_INTERVAL_MS = 50
PARAMETERIZATION_PREVIEW_INTERVAL_MS = 50
OPERATION_PREVIEW_WIDTH = 480
OPERATION_PREVIEW_HEIGHT = 270
OPERATION_PREVIEW_INTERVAL_MS = 50
OPERATION_RESULT_DISPLAY_MS = 3000
